name: Build RustHound

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Clone RustHound
      run: |
        git clone https://github.com/OPENCYBER-FR/RustHound
    - name: Build RustHound
      run: |
        cd RustHound
        docker build -t rusthound .
        docker run -v $(pwd):/usr/src/rusthound --name rusthound_windows rusthound windows
        docker run -v $(pwd):/usr/src/rusthound --name rusthound_linux_musl rusthound linux_musl
    - name: Copy RustHound
      run: |
        mkdir -p OPENCYBER-FR.RustHound
        cp RustHound/rusthound* OPENCYBER-FR.RustHound
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Build Rusthound: ${timestamp}" || exit 0
        git push
