name: Build RustHound

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Clone RustHound
      run: |
        git clone https://github.com/OPENCYBER-FR/RustHound
    - name: Build RustHound
      run: |
        cd RustHound
        docker build -t rusthound .
        docker run -v $(pwd):/usr/src/rusthound -d --name rusthound_windows rusthound windows
        docker run -v $(pwd):/usr/src/rusthound -d --name rusthound_linux_musl rusthound linux_musl
        docker run -v $(pwd):/usr/src/rusthound -d --name rusthound_macos rusthound macos
        echo "Waiting for RustHound builds to finish..."
        for i in {1..10}; do
          if docker exec rusthound_windows cargo --version && docker exec rusthound_linux_musl cargo --version && docker exec rusthound_macos cargo --version; then
            echo "All builds finished successfully."
            exit 0
          fi
          echo "Waiting for RustHound builds to finish... (attempt $i)"
          sleep 10
        done
        echo "Error: RustHound builds failed or timed out."
        exit 1
    - name: Copy RustHound
      run: |
        mkdir -p OPENCYBER-FR.RustHound
        cp RustHound/rusthound* OPENCYBER-FR.RustHound
    - name: Remove clone
      run: |
        rm -rf ./RustHound
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Build Rusthound: ${timestamp}" || exit 0
        git push
