name: Build RustHound

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Clone RustHound
      run: |
        git clone https://github.com/g0h4n/RustHound-CE
    - name: Get RustHound Dependencies
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        sudo apt install libssl-dev pkg-config -y
    - name: Build RustHound
      run: |
        cd RustHound-CE
        make linux_x86_64
    - name: Copy RustHound
      run: |
        mkdir -p g0h4n.RustHound-CE
        cp RustHound-CE/rusthound* g0h4n.RustHound-CE
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Build Rusthound: ${timestamp}" || exit 0
        git push
